[package]
name = "postgres-mcp"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0"
arc-swap = "1.7"
rmcp = { version = "0.1", features = [
  "server",
  "transport-sse-server",
  "transport-io",
] }
serde = { version = "1.0", features = ["derive"] }
sqlx = { version = "0.8", features = [
  "runtime-tokio",
  "tls-rustls-aws-lc-rs",
  "postgres",
] }
sqlparser = "0.55"
tokio = { version = "1.44", features = ["full"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
uuid = { version = "1.7", features = ["v4"] }
serde_json = "1.0.140"
